### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-angular#1073]
@next tag will be published with NativeScript Angular supporting Angular 5.
Please, use NativeScript Angular 4.4.1 to target Angular 4.

 - [x] [5.0.0-rc.0] - Merge initial support #1071
 - [x] Update nativescript-dev-webpack to work with the new AngularCompilerPlugin https://github.com/NativeScript/nativescript-dev-webpack/issues/311
 - [x] Update templates and NativeScript Angular apps to use Angular 5, TypeScript 2.4 (ngc depends on that version) and rxjs 5.5
 - [x] Update NativeScript Animations module to be compatible with Angular 5 Animations APIs
 - [ ] Research if the new [i18n tooling](https://angular.io/guide/i18n) can replace the nativescript-intl package. (https://github.com/NativeScript/nativescript-angular/issues/1133)

**Comment by mhadaily** [comment]
Hi, Just wondering which task is available and nobody is working on that?

**Comment by sis0k0** [comment]
@mhadaily, you can check out the brand new i18n stuff (https://angular.io/guide/i18n) in Angular 5 and how it fits in NativeScript. Right now, we are using NativeScript intl (https://github.com/nativescript/nativescript-intl) for localizations.

**Comment by jdnichollsc** [comment]
beautiful! haha

**Comment by itabo** [comment]
Any idea of estimation rc?. Great work!

**Comment by suburbanantihero** [comment]
Highly interested in this as well. 

Now that Angular 5 is out along with angular-cli 1.5, we want to leverage an nx-workspace generated project with both web and {N} apps.

**Comment by sean-perkins** [comment]
@suburbanantihero We are using NX for our NativeScript Angular and Web project, it works great!

**Comment by sis0k0** [comment]
animations PR: #1114

**Comment by crutchcorn** [comment]
Angular 5 animations were just merged: #1114. Is that what is being mentioned in this issue with animations mention?

**Comment by itabo** [comment]
Guys, any idea of RC date?. Thanks!

**Comment by sis0k0** [comment]
Released with 5.0.

**Comment by jdnichollsc** [comment]
Woww!! 💯
