### ISSUE TITLE
[Tracking] Angular 6

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-angular#1282]
Branch https://github.com/NativeScript/nativescript-angular/tree/sis0k0/ng6.

- [x] Update nativescript-dev-webpack to support webpack 4. https://github.com/NativeScript/nativescript-dev-webpack/issues/492
- [x] Enable strictMetadataEmit when https://github.com/angular/angular/issues/23310 is resolved. There's a PR in the Angular repo with the fix: https://github.com/angular/angular/pull/23349.
- [x]  [ActionBarExtension](https://github.com/NativeScript/nativescript-angular/blob/master/e2e/renderer/app/action-bar/action-bar-extension.component.ts) e2e test is failing when running webpack with uglify without specifying mangleExcludes. More specifically, the issue is reproducible when the name `ActionBar` is changed.
- [x] Verify that the unit tests are passing.
- [x] Update apps to Angular 6, rxjs 6 and TypeScript 2.7.2.
  - [x] sampleGroceries
  - [x] nativescript-sdk-examples
  - [x] tests-app-ng
  - [x] renderer/router e2e apps
  - [x] templates

**Comment by mr-White** [comment]
Watching this eagerly :)

**Comment by RainingNight** [comment]
Any news?

**Comment by NickIliev** [comment]
@RainingNight @mr-White the support for Angular 6 is in development but you can already test it with nativescript-angular@next (and then updating all Angular related dependencies with executing `./node_modules/.bin/update-app-ng-deps`) - test with POC app [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/next/package.json#L8-L38)

**Comment by mr-White** [comment]
Thank you @NickIliev ! I'll have to check it out this weekend :)

To anyone who hasn't subscribed to the NativeScript newsletter, in a recent issue, it mentioned that Angular 6 support is included in upcoming NativeScript 4.1 release.

Here is an except from that Newsletter:

> What’s Coming in NativeScript 4.1? 🧐
>
> Even though NativeScript 4.0 was just released, our engineering team has taken off the brakes and is steadily working towards the 4.1 release! Truth be told, this is bigger than most point releases, as we will be providing features and improvements such as:
>
>    V8 upgrade to latest version and performance improvements on Android;
>    Documentation revamp - complete revamp of the current cookbook, new table of contents, new user experience;
>    Various fixes on debugging and LiveSync; LiveSync will work with sockets to provide more stable and predictable experience;
>    **Support for Angular 6 and Webpack 4**;
    Extended CSS support with gradients, box shadow, and media queries;
    Debugging on multiple iOS simulators;
    New setup scripts for Windows and Mac.
>
> Stay tuned as 4.1 is due to drop at the very end of May or early June! As a reminder, [register for our upcoming webinar](https://register.gotowebinar.com/register/5221651479657103362?source=nativescript-news) to learn all about the 4.1 release.

/cc @RainingNight

**Comment by RoyiNamir** [comment]
@sis0k0  Regarding RXJS6 &  Angular 6 , there is a problem when importing operators in the new way.
aka 

`import {map} from 'rxjs/operators'

(`from 'rxjs/operators/map'` is **not** supported anymore)


In short : all operators (from `rxjs/opearators`) will be imported regardless their usage. ( for dev and for bundling with webpack also)

Webpack configuration must be added with code in order not to import all unused operators


Already reported this here :  https://github.com/NativeScript/nativescript-dev-webpack/issues/550
